
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Alignment alignment12;

	private global::Gtk.VBox vbox10;

	private global::Gtk.Label lbHelp;

	private global::Gtk.HBox hbox15;

	private global::Gtk.Button btnEnterUserLogin;

	private global::Gtk.Button btnEnterAdminLogin;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Sistema EyS");
		this.WindowPosition = ((global::Gtk.WindowPosition)(1));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.alignment12 = new global::Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
		this.alignment12.Name = "alignment12";
		this.alignment12.LeftPadding = ((uint)(10));
		this.alignment12.TopPadding = ((uint)(10));
		this.alignment12.RightPadding = ((uint)(10));
		this.alignment12.BottomPadding = ((uint)(10));
		// Container child alignment12.Gtk.Container+ContainerChild
		this.vbox10 = new global::Gtk.VBox();
		this.vbox10.Name = "vbox10";
		this.vbox10.Homogeneous = true;
		this.vbox10.Spacing = 30;
		// Container child vbox10.Gtk.Box+BoxChild
		this.lbHelp = new global::Gtk.Label();
		this.lbHelp.Name = "lbHelp";
		this.lbHelp.LabelProp = global::Mono.Unix.Catalog.GetString("Seleccione su método para iniciar sesión en el sistema");
		this.lbHelp.Justify = ((global::Gtk.Justification)(2));
		this.vbox10.Add(this.lbHelp);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.lbHelp]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox10.Gtk.Box+BoxChild
		this.hbox15 = new global::Gtk.HBox();
		this.hbox15.Name = "hbox15";
		this.hbox15.Spacing = 6;
		// Container child hbox15.Gtk.Box+BoxChild
		this.btnEnterUserLogin = new global::Gtk.Button();
		this.btnEnterUserLogin.CanFocus = true;
		this.btnEnterUserLogin.Name = "btnEnterUserLogin";
		this.btnEnterUserLogin.UseUnderline = true;
		this.btnEnterUserLogin.Label = global::Mono.Unix.Catalog.GetString("Empleado");
		this.hbox15.Add(this.btnEnterUserLogin);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox15[this.btnEnterUserLogin]));
		w2.Position = 0;
		w2.Fill = false;
		// Container child hbox15.Gtk.Box+BoxChild
		this.btnEnterAdminLogin = new global::Gtk.Button();
		this.btnEnterAdminLogin.CanFocus = true;
		this.btnEnterAdminLogin.Name = "btnEnterAdminLogin";
		this.btnEnterAdminLogin.UseUnderline = true;
		this.btnEnterAdminLogin.Label = global::Mono.Unix.Catalog.GetString("Administrador");
		this.hbox15.Add(this.btnEnterAdminLogin);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox15[this.btnEnterAdminLogin]));
		w3.Position = 1;
		w3.Fill = false;
		this.vbox10.Add(this.hbox15);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.hbox15]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		this.alignment12.Add(this.vbox10);
		this.Add(this.alignment12);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 432;
		this.DefaultHeight = 254;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.btnEnterUserLogin.Clicked += new global::System.EventHandler(this.btnEnterUserLoginOnClicked);
		this.btnEnterAdminLogin.Clicked += new global::System.EventHandler(this.btnEnterAdminLoginOnClicked);
	}
}
