
// This file has been generated by the GUI designer. Do not modify.
namespace SistemaEyS.AdminForms.Tables.HorPanelBtn
{
	public partial class AddDialogHor
	{
		private global::Gtk.Alignment alignment17;

		private global::Gtk.VBox vbox5;

		private global::Gtk.Alignment alignment21;

		private global::Gtk.VBox vbox10;

		private global::Gtk.Alignment alignment1;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Label label1;

		private global::Gtk.Entry TxtName;

		private global::Gtk.Alignment alignment23;

		private global::Gtk.HBox hbox19;

		private global::Gtk.VBox vbox2;

		private global::Gtk.Label label5;

		private global::Gtk.ComboBoxEntry lunesSal;

		private global::Gtk.VBox vbox1;

		private global::Gtk.Label label3;

		private global::Gtk.ComboBoxEntry lunesIni;

		private global::Gtk.VBox vbox3;

		private global::Gtk.Label label9;

		private global::Gtk.Alignment alignment24;

		private global::Gtk.HBox hbox20;

		private global::Gtk.ComboBoxEntry martesSal;

		private global::Gtk.ComboBoxEntry martesIni;

		private global::Gtk.Label label10;

		private global::Gtk.Alignment alignment25;

		private global::Gtk.HBox hbox21;

		private global::Gtk.ComboBoxEntry miercolesSal;

		private global::Gtk.ComboBoxEntry miercolesIni;

		private global::Gtk.Label label11;

		private global::Gtk.Alignment alignment26;

		private global::Gtk.HBox hbox22;

		private global::Gtk.ComboBoxEntry juevesSal;

		private global::Gtk.ComboBoxEntry juevesIni;

		private global::Gtk.Label label12;

		private global::Gtk.Alignment alignment27;

		private global::Gtk.HBox hbox23;

		private global::Gtk.ComboBoxEntry viernesSal;

		private global::Gtk.ComboBoxEntry viernesIni;

		private global::Gtk.Label label13;

		private global::Gtk.Alignment alignment28;

		private global::Gtk.HBox hbox24;

		private global::Gtk.ComboBoxEntry sabadoSal;

		private global::Gtk.ComboBoxEntry sabadoIni;

		private global::Gtk.Label label14;

		private global::Gtk.Alignment alignment29;

		private global::Gtk.HBox hbox25;

		private global::Gtk.ComboBoxEntry domingoSal;

		private global::Gtk.ComboBoxEntry domingoIni;

		private global::Gtk.Label label15;

		private global::Gtk.Alignment alignment18;

		private global::Gtk.HBox hbox7;

		private global::Gtk.Button BtnSave;

		private global::Gtk.Button BtnCancel;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget SistemaEyS.AdminForms.Tables.HorPanelBtn.AddDialogHor
			this.Name = "SistemaEyS.AdminForms.Tables.HorPanelBtn.AddDialogHor";
			this.Title = global::Mono.Unix.Catalog.GetString("AddDialogHor");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child SistemaEyS.AdminForms.Tables.HorPanelBtn.AddDialogHor.Gtk.Container+ContainerChild
			this.alignment17 = new global::Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
			this.alignment17.Name = "alignment17";
			this.alignment17.BorderWidth = ((uint)(10));
			// Container child alignment17.Gtk.Container+ContainerChild
			this.vbox5 = new global::Gtk.VBox();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.alignment21 = new global::Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
			this.alignment21.Name = "alignment21";
			// Container child alignment21.Gtk.Container+ContainerChild
			this.vbox10 = new global::Gtk.VBox();
			this.vbox10.Name = "vbox10";
			this.vbox10.Spacing = 6;
			// Container child vbox10.Gtk.Box+BoxChild
			this.alignment1 = new global::Gtk.Alignment(0.5F, 0.5F, 0F, 1F);
			this.alignment1.Name = "alignment1";
			// Container child alignment1.Gtk.Container+ContainerChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Nombre:");
			this.hbox2.Add(this.label1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.label1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.TxtName = new global::Gtk.Entry();
			this.TxtName.CanFocus = true;
			this.TxtName.Name = "TxtName";
			this.TxtName.IsEditable = true;
			this.TxtName.InvisibleChar = '●';
			this.hbox2.Add(this.TxtName);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.TxtName]));
			w2.Position = 1;
			this.alignment1.Add(this.hbox2);
			this.vbox10.Add(this.alignment1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.alignment1]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			w4.Padding = ((uint)(10));
			// Container child vbox10.Gtk.Box+BoxChild
			this.alignment23 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment23.Name = "alignment23";
			// Container child alignment23.Gtk.Container+ContainerChild
			this.hbox19 = new global::Gtk.HBox();
			this.hbox19.Name = "hbox19";
			this.hbox19.Spacing = 6;
			// Container child hbox19.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Salida");
			this.vbox2.Add(this.label5);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.label5]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.lunesSal = global::Gtk.ComboBoxEntry.NewText();
			this.lunesSal.AppendText(global::Mono.Unix.Catalog.GetString("8:00"));
			this.lunesSal.AppendText(global::Mono.Unix.Catalog.GetString("9:00"));
			this.lunesSal.AppendText(global::Mono.Unix.Catalog.GetString("10:00"));
			this.lunesSal.AppendText(global::Mono.Unix.Catalog.GetString("11:00"));
			this.lunesSal.AppendText(global::Mono.Unix.Catalog.GetString("12:00"));
			this.lunesSal.AppendText(global::Mono.Unix.Catalog.GetString("13:00"));
			this.lunesSal.AppendText(global::Mono.Unix.Catalog.GetString("14:00"));
			this.lunesSal.AppendText(global::Mono.Unix.Catalog.GetString("15:00"));
			this.lunesSal.AppendText(global::Mono.Unix.Catalog.GetString("16:00"));
			this.lunesSal.AppendText(global::Mono.Unix.Catalog.GetString("17:00"));
			this.lunesSal.Name = "lunesSal";
			this.vbox2.Add(this.lunesSal);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.lunesSal]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			this.hbox19.Add(this.vbox2);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox19[this.vbox2]));
			w7.PackType = ((global::Gtk.PackType)(1));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox19.Gtk.Box+BoxChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Entrada");
			this.vbox1.Add(this.label3);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.label3]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.lunesIni = global::Gtk.ComboBoxEntry.NewText();
			this.lunesIni.AppendText(global::Mono.Unix.Catalog.GetString("8:00"));
			this.lunesIni.AppendText(global::Mono.Unix.Catalog.GetString("9:00"));
			this.lunesIni.AppendText(global::Mono.Unix.Catalog.GetString("10:00"));
			this.lunesIni.AppendText(global::Mono.Unix.Catalog.GetString("11:00"));
			this.lunesIni.AppendText(global::Mono.Unix.Catalog.GetString("12:00"));
			this.lunesIni.AppendText(global::Mono.Unix.Catalog.GetString("13:00"));
			this.lunesIni.AppendText(global::Mono.Unix.Catalog.GetString("14:00"));
			this.lunesIni.AppendText(global::Mono.Unix.Catalog.GetString("15:00"));
			this.lunesIni.AppendText(global::Mono.Unix.Catalog.GetString("16:00"));
			this.lunesIni.AppendText(global::Mono.Unix.Catalog.GetString("17:00"));
			this.lunesIni.Name = "lunesIni";
			this.vbox1.Add(this.lunesIni);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.lunesIni]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			this.hbox19.Add(this.vbox1);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox19[this.vbox1]));
			w10.PackType = ((global::Gtk.PackType)(1));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hbox19.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox();
			this.vbox3.Name = "vbox3";
			// Container child vbox3.Gtk.Box+BoxChild
			this.label9 = new global::Gtk.Label();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString("Lunes:");
			this.label9.Justify = ((global::Gtk.Justification)(1));
			this.vbox3.Add(this.label9);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.label9]));
			w11.PackType = ((global::Gtk.PackType)(1));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			w11.Padding = ((uint)(10));
			this.hbox19.Add(this.vbox3);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox19[this.vbox3]));
			w12.PackType = ((global::Gtk.PackType)(1));
			w12.Position = 2;
			w12.Expand = false;
			this.alignment23.Add(this.hbox19);
			this.vbox10.Add(this.alignment23);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.alignment23]));
			w14.Position = 1;
			w14.Expand = false;
			w14.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.alignment24 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment24.Name = "alignment24";
			// Container child alignment24.Gtk.Container+ContainerChild
			this.hbox20 = new global::Gtk.HBox();
			this.hbox20.Name = "hbox20";
			this.hbox20.Spacing = 6;
			// Container child hbox20.Gtk.Box+BoxChild
			this.martesSal = global::Gtk.ComboBoxEntry.NewText();
			this.martesSal.AppendText(global::Mono.Unix.Catalog.GetString("8:00"));
			this.martesSal.AppendText(global::Mono.Unix.Catalog.GetString("9:00"));
			this.martesSal.AppendText(global::Mono.Unix.Catalog.GetString("10:00"));
			this.martesSal.AppendText(global::Mono.Unix.Catalog.GetString("11:00"));
			this.martesSal.AppendText(global::Mono.Unix.Catalog.GetString("12:00"));
			this.martesSal.AppendText(global::Mono.Unix.Catalog.GetString("13:00"));
			this.martesSal.AppendText(global::Mono.Unix.Catalog.GetString("14:00"));
			this.martesSal.AppendText(global::Mono.Unix.Catalog.GetString("15:00"));
			this.martesSal.AppendText(global::Mono.Unix.Catalog.GetString("16:00"));
			this.martesSal.AppendText(global::Mono.Unix.Catalog.GetString("17:00"));
			this.martesSal.Name = "martesSal";
			this.hbox20.Add(this.martesSal);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox20[this.martesSal]));
			w15.PackType = ((global::Gtk.PackType)(1));
			w15.Position = 0;
			w15.Expand = false;
			w15.Fill = false;
			// Container child hbox20.Gtk.Box+BoxChild
			this.martesIni = global::Gtk.ComboBoxEntry.NewText();
			this.martesIni.AppendText(global::Mono.Unix.Catalog.GetString("8:00"));
			this.martesIni.AppendText(global::Mono.Unix.Catalog.GetString("9:00"));
			this.martesIni.AppendText(global::Mono.Unix.Catalog.GetString("10:00"));
			this.martesIni.AppendText(global::Mono.Unix.Catalog.GetString("11:00"));
			this.martesIni.AppendText(global::Mono.Unix.Catalog.GetString("12:00"));
			this.martesIni.AppendText(global::Mono.Unix.Catalog.GetString("13:00"));
			this.martesIni.AppendText(global::Mono.Unix.Catalog.GetString("14:00"));
			this.martesIni.AppendText(global::Mono.Unix.Catalog.GetString("15:00"));
			this.martesIni.AppendText(global::Mono.Unix.Catalog.GetString("16:00"));
			this.martesIni.AppendText(global::Mono.Unix.Catalog.GetString("17:00"));
			this.martesIni.Name = "martesIni";
			this.hbox20.Add(this.martesIni);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox20[this.martesIni]));
			w16.PackType = ((global::Gtk.PackType)(1));
			w16.Position = 1;
			w16.Expand = false;
			w16.Fill = false;
			// Container child hbox20.Gtk.Box+BoxChild
			this.label10 = new global::Gtk.Label();
			this.label10.Name = "label10";
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString("Martes:");
			this.hbox20.Add(this.label10);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox20[this.label10]));
			w17.PackType = ((global::Gtk.PackType)(1));
			w17.Position = 2;
			w17.Expand = false;
			w17.Fill = false;
			this.alignment24.Add(this.hbox20);
			this.vbox10.Add(this.alignment24);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.alignment24]));
			w19.Position = 2;
			w19.Expand = false;
			w19.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.alignment25 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment25.Name = "alignment25";
			// Container child alignment25.Gtk.Container+ContainerChild
			this.hbox21 = new global::Gtk.HBox();
			this.hbox21.Name = "hbox21";
			this.hbox21.Spacing = 6;
			// Container child hbox21.Gtk.Box+BoxChild
			this.miercolesSal = global::Gtk.ComboBoxEntry.NewText();
			this.miercolesSal.AppendText(global::Mono.Unix.Catalog.GetString("8:00"));
			this.miercolesSal.AppendText(global::Mono.Unix.Catalog.GetString("9:00"));
			this.miercolesSal.AppendText(global::Mono.Unix.Catalog.GetString("10:00"));
			this.miercolesSal.AppendText(global::Mono.Unix.Catalog.GetString("11:00"));
			this.miercolesSal.AppendText(global::Mono.Unix.Catalog.GetString("12:00"));
			this.miercolesSal.AppendText(global::Mono.Unix.Catalog.GetString("13:00"));
			this.miercolesSal.AppendText(global::Mono.Unix.Catalog.GetString("14:00"));
			this.miercolesSal.AppendText(global::Mono.Unix.Catalog.GetString("15:00"));
			this.miercolesSal.AppendText(global::Mono.Unix.Catalog.GetString("16:00"));
			this.miercolesSal.AppendText(global::Mono.Unix.Catalog.GetString("17:00"));
			this.miercolesSal.Name = "miercolesSal";
			this.hbox21.Add(this.miercolesSal);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox21[this.miercolesSal]));
			w20.PackType = ((global::Gtk.PackType)(1));
			w20.Position = 0;
			w20.Expand = false;
			w20.Fill = false;
			// Container child hbox21.Gtk.Box+BoxChild
			this.miercolesIni = global::Gtk.ComboBoxEntry.NewText();
			this.miercolesIni.AppendText(global::Mono.Unix.Catalog.GetString("8:00"));
			this.miercolesIni.AppendText(global::Mono.Unix.Catalog.GetString("9:00"));
			this.miercolesIni.AppendText(global::Mono.Unix.Catalog.GetString("10:00"));
			this.miercolesIni.AppendText(global::Mono.Unix.Catalog.GetString("11:00"));
			this.miercolesIni.AppendText(global::Mono.Unix.Catalog.GetString("12:00"));
			this.miercolesIni.AppendText(global::Mono.Unix.Catalog.GetString("13:00"));
			this.miercolesIni.AppendText(global::Mono.Unix.Catalog.GetString("14:00"));
			this.miercolesIni.AppendText(global::Mono.Unix.Catalog.GetString("15:00"));
			this.miercolesIni.AppendText(global::Mono.Unix.Catalog.GetString("16:00"));
			this.miercolesIni.AppendText(global::Mono.Unix.Catalog.GetString("17:00"));
			this.miercolesIni.Name = "miercolesIni";
			this.hbox21.Add(this.miercolesIni);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox21[this.miercolesIni]));
			w21.PackType = ((global::Gtk.PackType)(1));
			w21.Position = 1;
			w21.Expand = false;
			w21.Fill = false;
			// Container child hbox21.Gtk.Box+BoxChild
			this.label11 = new global::Gtk.Label();
			this.label11.Name = "label11";
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString("Miercoles:");
			this.hbox21.Add(this.label11);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox21[this.label11]));
			w22.PackType = ((global::Gtk.PackType)(1));
			w22.Position = 2;
			w22.Expand = false;
			w22.Fill = false;
			this.alignment25.Add(this.hbox21);
			this.vbox10.Add(this.alignment25);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.alignment25]));
			w24.Position = 3;
			w24.Expand = false;
			w24.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.alignment26 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment26.Name = "alignment26";
			// Container child alignment26.Gtk.Container+ContainerChild
			this.hbox22 = new global::Gtk.HBox();
			this.hbox22.Name = "hbox22";
			this.hbox22.Spacing = 6;
			// Container child hbox22.Gtk.Box+BoxChild
			this.juevesSal = global::Gtk.ComboBoxEntry.NewText();
			this.juevesSal.AppendText(global::Mono.Unix.Catalog.GetString("8:00"));
			this.juevesSal.AppendText(global::Mono.Unix.Catalog.GetString("9:00"));
			this.juevesSal.AppendText(global::Mono.Unix.Catalog.GetString("10:00"));
			this.juevesSal.AppendText(global::Mono.Unix.Catalog.GetString("11:00"));
			this.juevesSal.AppendText(global::Mono.Unix.Catalog.GetString("12:00"));
			this.juevesSal.AppendText(global::Mono.Unix.Catalog.GetString("13:00"));
			this.juevesSal.AppendText(global::Mono.Unix.Catalog.GetString("14:00"));
			this.juevesSal.AppendText(global::Mono.Unix.Catalog.GetString("15:00"));
			this.juevesSal.AppendText(global::Mono.Unix.Catalog.GetString("16:00"));
			this.juevesSal.AppendText(global::Mono.Unix.Catalog.GetString("17:00"));
			this.juevesSal.Name = "juevesSal";
			this.hbox22.Add(this.juevesSal);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox22[this.juevesSal]));
			w25.PackType = ((global::Gtk.PackType)(1));
			w25.Position = 0;
			w25.Expand = false;
			w25.Fill = false;
			// Container child hbox22.Gtk.Box+BoxChild
			this.juevesIni = global::Gtk.ComboBoxEntry.NewText();
			this.juevesIni.AppendText(global::Mono.Unix.Catalog.GetString("8:00"));
			this.juevesIni.AppendText(global::Mono.Unix.Catalog.GetString("9:00"));
			this.juevesIni.AppendText(global::Mono.Unix.Catalog.GetString("10:00"));
			this.juevesIni.AppendText(global::Mono.Unix.Catalog.GetString("11:00"));
			this.juevesIni.AppendText(global::Mono.Unix.Catalog.GetString("12:00"));
			this.juevesIni.AppendText(global::Mono.Unix.Catalog.GetString("13:00"));
			this.juevesIni.AppendText(global::Mono.Unix.Catalog.GetString("14:00"));
			this.juevesIni.AppendText(global::Mono.Unix.Catalog.GetString("15:00"));
			this.juevesIni.AppendText(global::Mono.Unix.Catalog.GetString("16:00"));
			this.juevesIni.AppendText(global::Mono.Unix.Catalog.GetString("17:00"));
			this.juevesIni.Name = "juevesIni";
			this.hbox22.Add(this.juevesIni);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox22[this.juevesIni]));
			w26.PackType = ((global::Gtk.PackType)(1));
			w26.Position = 1;
			w26.Expand = false;
			w26.Fill = false;
			// Container child hbox22.Gtk.Box+BoxChild
			this.label12 = new global::Gtk.Label();
			this.label12.Name = "label12";
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString("Jueves:");
			this.hbox22.Add(this.label12);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox22[this.label12]));
			w27.PackType = ((global::Gtk.PackType)(1));
			w27.Position = 2;
			w27.Expand = false;
			w27.Fill = false;
			this.alignment26.Add(this.hbox22);
			this.vbox10.Add(this.alignment26);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.alignment26]));
			w29.Position = 4;
			w29.Expand = false;
			w29.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.alignment27 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment27.Name = "alignment27";
			// Container child alignment27.Gtk.Container+ContainerChild
			this.hbox23 = new global::Gtk.HBox();
			this.hbox23.Name = "hbox23";
			this.hbox23.Spacing = 6;
			// Container child hbox23.Gtk.Box+BoxChild
			this.viernesSal = global::Gtk.ComboBoxEntry.NewText();
			this.viernesSal.AppendText(global::Mono.Unix.Catalog.GetString("8:00"));
			this.viernesSal.AppendText(global::Mono.Unix.Catalog.GetString("9:00"));
			this.viernesSal.AppendText(global::Mono.Unix.Catalog.GetString("10:00"));
			this.viernesSal.AppendText(global::Mono.Unix.Catalog.GetString("11:00"));
			this.viernesSal.AppendText(global::Mono.Unix.Catalog.GetString("12:00"));
			this.viernesSal.AppendText(global::Mono.Unix.Catalog.GetString("13:00"));
			this.viernesSal.AppendText(global::Mono.Unix.Catalog.GetString("14:00"));
			this.viernesSal.AppendText(global::Mono.Unix.Catalog.GetString("15:00"));
			this.viernesSal.AppendText(global::Mono.Unix.Catalog.GetString("16:00"));
			this.viernesSal.AppendText(global::Mono.Unix.Catalog.GetString("17:00"));
			this.viernesSal.Name = "viernesSal";
			this.hbox23.Add(this.viernesSal);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox23[this.viernesSal]));
			w30.PackType = ((global::Gtk.PackType)(1));
			w30.Position = 0;
			w30.Expand = false;
			w30.Fill = false;
			// Container child hbox23.Gtk.Box+BoxChild
			this.viernesIni = global::Gtk.ComboBoxEntry.NewText();
			this.viernesIni.AppendText(global::Mono.Unix.Catalog.GetString("8:00"));
			this.viernesIni.AppendText(global::Mono.Unix.Catalog.GetString("9:00"));
			this.viernesIni.AppendText(global::Mono.Unix.Catalog.GetString("10:00"));
			this.viernesIni.AppendText(global::Mono.Unix.Catalog.GetString("11:00"));
			this.viernesIni.AppendText(global::Mono.Unix.Catalog.GetString("12:00"));
			this.viernesIni.AppendText(global::Mono.Unix.Catalog.GetString("13:00"));
			this.viernesIni.AppendText(global::Mono.Unix.Catalog.GetString("14:00"));
			this.viernesIni.AppendText(global::Mono.Unix.Catalog.GetString("15:00"));
			this.viernesIni.AppendText(global::Mono.Unix.Catalog.GetString("16:00"));
			this.viernesIni.AppendText(global::Mono.Unix.Catalog.GetString("17:00"));
			this.viernesIni.Name = "viernesIni";
			this.hbox23.Add(this.viernesIni);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hbox23[this.viernesIni]));
			w31.PackType = ((global::Gtk.PackType)(1));
			w31.Position = 1;
			w31.Expand = false;
			w31.Fill = false;
			// Container child hbox23.Gtk.Box+BoxChild
			this.label13 = new global::Gtk.Label();
			this.label13.Name = "label13";
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString("Viernes:");
			this.hbox23.Add(this.label13);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hbox23[this.label13]));
			w32.PackType = ((global::Gtk.PackType)(1));
			w32.Position = 2;
			w32.Expand = false;
			w32.Fill = false;
			this.alignment27.Add(this.hbox23);
			this.vbox10.Add(this.alignment27);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.alignment27]));
			w34.Position = 5;
			w34.Expand = false;
			w34.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.alignment28 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment28.Name = "alignment28";
			// Container child alignment28.Gtk.Container+ContainerChild
			this.hbox24 = new global::Gtk.HBox();
			this.hbox24.Name = "hbox24";
			this.hbox24.Spacing = 6;
			// Container child hbox24.Gtk.Box+BoxChild
			this.sabadoSal = global::Gtk.ComboBoxEntry.NewText();
			this.sabadoSal.AppendText(global::Mono.Unix.Catalog.GetString("8:00"));
			this.sabadoSal.AppendText(global::Mono.Unix.Catalog.GetString("9:00"));
			this.sabadoSal.AppendText(global::Mono.Unix.Catalog.GetString("10:00"));
			this.sabadoSal.AppendText(global::Mono.Unix.Catalog.GetString("11:00"));
			this.sabadoSal.AppendText(global::Mono.Unix.Catalog.GetString("12:00"));
			this.sabadoSal.AppendText(global::Mono.Unix.Catalog.GetString("13:00"));
			this.sabadoSal.AppendText(global::Mono.Unix.Catalog.GetString("14:00"));
			this.sabadoSal.AppendText(global::Mono.Unix.Catalog.GetString("15:00"));
			this.sabadoSal.AppendText(global::Mono.Unix.Catalog.GetString("16:00"));
			this.sabadoSal.AppendText(global::Mono.Unix.Catalog.GetString("17:00"));
			this.sabadoSal.Name = "sabadoSal";
			this.hbox24.Add(this.sabadoSal);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.hbox24[this.sabadoSal]));
			w35.PackType = ((global::Gtk.PackType)(1));
			w35.Position = 0;
			w35.Expand = false;
			w35.Fill = false;
			// Container child hbox24.Gtk.Box+BoxChild
			this.sabadoIni = global::Gtk.ComboBoxEntry.NewText();
			this.sabadoIni.AppendText(global::Mono.Unix.Catalog.GetString("8:00"));
			this.sabadoIni.AppendText(global::Mono.Unix.Catalog.GetString("9:00"));
			this.sabadoIni.AppendText(global::Mono.Unix.Catalog.GetString("10:00"));
			this.sabadoIni.AppendText(global::Mono.Unix.Catalog.GetString("11:00"));
			this.sabadoIni.AppendText(global::Mono.Unix.Catalog.GetString("12:00"));
			this.sabadoIni.AppendText(global::Mono.Unix.Catalog.GetString("13:00"));
			this.sabadoIni.AppendText(global::Mono.Unix.Catalog.GetString("14:00"));
			this.sabadoIni.AppendText(global::Mono.Unix.Catalog.GetString("15:00"));
			this.sabadoIni.AppendText(global::Mono.Unix.Catalog.GetString("16:00"));
			this.sabadoIni.AppendText(global::Mono.Unix.Catalog.GetString("17:00"));
			this.sabadoIni.Name = "sabadoIni";
			this.hbox24.Add(this.sabadoIni);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.hbox24[this.sabadoIni]));
			w36.PackType = ((global::Gtk.PackType)(1));
			w36.Position = 1;
			w36.Expand = false;
			w36.Fill = false;
			// Container child hbox24.Gtk.Box+BoxChild
			this.label14 = new global::Gtk.Label();
			this.label14.Name = "label14";
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString("Sabado:");
			this.hbox24.Add(this.label14);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.hbox24[this.label14]));
			w37.PackType = ((global::Gtk.PackType)(1));
			w37.Position = 2;
			w37.Expand = false;
			w37.Fill = false;
			this.alignment28.Add(this.hbox24);
			this.vbox10.Add(this.alignment28);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.alignment28]));
			w39.Position = 6;
			w39.Expand = false;
			w39.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.alignment29 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment29.Name = "alignment29";
			// Container child alignment29.Gtk.Container+ContainerChild
			this.hbox25 = new global::Gtk.HBox();
			this.hbox25.Name = "hbox25";
			this.hbox25.Spacing = 6;
			// Container child hbox25.Gtk.Box+BoxChild
			this.domingoSal = global::Gtk.ComboBoxEntry.NewText();
			this.domingoSal.AppendText(global::Mono.Unix.Catalog.GetString("8:00"));
			this.domingoSal.AppendText(global::Mono.Unix.Catalog.GetString("9:00"));
			this.domingoSal.AppendText(global::Mono.Unix.Catalog.GetString("10:00"));
			this.domingoSal.AppendText(global::Mono.Unix.Catalog.GetString("11:00"));
			this.domingoSal.AppendText(global::Mono.Unix.Catalog.GetString("12:00"));
			this.domingoSal.AppendText(global::Mono.Unix.Catalog.GetString("13:00"));
			this.domingoSal.AppendText(global::Mono.Unix.Catalog.GetString("14:00"));
			this.domingoSal.AppendText(global::Mono.Unix.Catalog.GetString("15:00"));
			this.domingoSal.AppendText(global::Mono.Unix.Catalog.GetString("16:00"));
			this.domingoSal.AppendText(global::Mono.Unix.Catalog.GetString("17:00"));
			this.domingoSal.Name = "domingoSal";
			this.hbox25.Add(this.domingoSal);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.hbox25[this.domingoSal]));
			w40.PackType = ((global::Gtk.PackType)(1));
			w40.Position = 0;
			w40.Expand = false;
			w40.Fill = false;
			// Container child hbox25.Gtk.Box+BoxChild
			this.domingoIni = global::Gtk.ComboBoxEntry.NewText();
			this.domingoIni.AppendText(global::Mono.Unix.Catalog.GetString("8:00"));
			this.domingoIni.AppendText(global::Mono.Unix.Catalog.GetString("9:00"));
			this.domingoIni.AppendText(global::Mono.Unix.Catalog.GetString("10:00"));
			this.domingoIni.AppendText(global::Mono.Unix.Catalog.GetString("11:00"));
			this.domingoIni.AppendText(global::Mono.Unix.Catalog.GetString("12:00"));
			this.domingoIni.AppendText(global::Mono.Unix.Catalog.GetString("13:00"));
			this.domingoIni.AppendText(global::Mono.Unix.Catalog.GetString("14:00"));
			this.domingoIni.AppendText(global::Mono.Unix.Catalog.GetString("15:00"));
			this.domingoIni.AppendText(global::Mono.Unix.Catalog.GetString("16:00"));
			this.domingoIni.AppendText(global::Mono.Unix.Catalog.GetString("17:00"));
			this.domingoIni.Name = "domingoIni";
			this.hbox25.Add(this.domingoIni);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.hbox25[this.domingoIni]));
			w41.PackType = ((global::Gtk.PackType)(1));
			w41.Position = 1;
			w41.Expand = false;
			w41.Fill = false;
			// Container child hbox25.Gtk.Box+BoxChild
			this.label15 = new global::Gtk.Label();
			this.label15.Name = "label15";
			this.label15.LabelProp = global::Mono.Unix.Catalog.GetString("Domingo:");
			this.hbox25.Add(this.label15);
			global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.hbox25[this.label15]));
			w42.PackType = ((global::Gtk.PackType)(1));
			w42.Position = 2;
			w42.Expand = false;
			w42.Fill = false;
			this.alignment29.Add(this.hbox25);
			this.vbox10.Add(this.alignment29);
			global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.alignment29]));
			w44.Position = 7;
			w44.Expand = false;
			w44.Fill = false;
			this.alignment21.Add(this.vbox10);
			this.vbox5.Add(this.alignment21);
			global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.alignment21]));
			w46.Position = 0;
			w46.Expand = false;
			w46.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.alignment18 = new global::Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
			this.alignment18.Name = "alignment18";
			this.alignment18.BorderWidth = ((uint)(20));
			// Container child alignment18.Gtk.Container+ContainerChild
			this.hbox7 = new global::Gtk.HBox();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 10;
			// Container child hbox7.Gtk.Box+BoxChild
			this.BtnSave = new global::Gtk.Button();
			this.BtnSave.CanFocus = true;
			this.BtnSave.Name = "BtnSave";
			this.BtnSave.UseUnderline = true;
			this.BtnSave.Label = global::Mono.Unix.Catalog.GetString("Guardar");
			global::Gtk.Image w47 = new global::Gtk.Image();
			w47.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-apply", global::Gtk.IconSize.Menu);
			this.BtnSave.Image = w47;
			this.hbox7.Add(this.BtnSave);
			global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.BtnSave]));
			w48.Position = 0;
			w48.Expand = false;
			w48.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.BtnCancel = new global::Gtk.Button();
			this.BtnCancel.CanFocus = true;
			this.BtnCancel.Name = "BtnCancel";
			this.BtnCancel.UseUnderline = true;
			this.BtnCancel.Label = global::Mono.Unix.Catalog.GetString("Cancelar");
			global::Gtk.Image w49 = new global::Gtk.Image();
			w49.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-cancel", global::Gtk.IconSize.Menu);
			this.BtnCancel.Image = w49;
			this.hbox7.Add(this.BtnCancel);
			global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.BtnCancel]));
			w50.Position = 1;
			w50.Expand = false;
			w50.Fill = false;
			this.alignment18.Add(this.hbox7);
			this.vbox5.Add(this.alignment18);
			global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.alignment18]));
			w52.Position = 1;
			w52.Expand = false;
			w52.Fill = false;
			this.alignment17.Add(this.vbox5);
			this.Add(this.alignment17);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 550;
			this.DefaultHeight = 434;
			this.Show();
			this.BtnSave.Clicked += new global::System.EventHandler(this.BtnSaveOnClicked);
			this.BtnCancel.Clicked += new global::System.EventHandler(this.BtnCancelOnClicked);
		}
	}
}
