
// This file has been generated by the GUI designer. Do not modify.
namespace SistemaEyS.AdminForms.Tables.EmpPanelBtn
{
	public partial class ValidBtn
	{
		private global::Gtk.VBox vbox6;

		private global::Gtk.Alignment alignment12;

		private global::Gtk.Label label21;

		private global::Gtk.HBox hbox10;

		private global::Gtk.Alignment alignment14;

		private global::Gtk.Alignment alignment16;

		private global::Gtk.Label label23;

		private global::Gtk.VBox vbox7;

		private global::Gtk.VBox vbox9;

		private global::Gtk.HBox hbox12;

		private global::Gtk.Label label16;

		private global::Gtk.Image image1;

		private global::Gtk.HBox hbox13;

		private global::Gtk.Label label17;

		private global::Gtk.Image image2;

		private global::Gtk.VBox vbox8;

		private global::Gtk.HBox hbox14;

		private global::Gtk.Label label18;

		private global::Gtk.Image image3;

		private global::Gtk.HBox hbox15;

		private global::Gtk.Label label19;

		private global::Gtk.Image image4;

		private global::Gtk.Alignment alignment13;

		private global::Gtk.Label label22;

		private global::Gtk.HBox hbox16;

		private global::Gtk.Alignment alignment17;

		private global::Gtk.Label label25;

		private global::Gtk.HBox hbox17;

		private global::Gtk.Alignment alignment11;

		private global::Gtk.Button button6;

		private global::Gtk.Alignment alignment10;

		private global::Gtk.Button button5;

		private global::Gtk.Alignment alignment15;

		private global::Gtk.Label label24;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget SistemaEyS.AdminForms.Tables.EmpPanelBtn.ValidBtn
			this.Name = "SistemaEyS.AdminForms.Tables.EmpPanelBtn.ValidBtn";
			this.Title = global::Mono.Unix.Catalog.GetString("ValidBtn");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child SistemaEyS.AdminForms.Tables.EmpPanelBtn.ValidBtn.Gtk.Container+ContainerChild
			this.vbox6 = new global::Gtk.VBox();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.alignment12 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment12.Name = "alignment12";
			this.alignment12.BorderWidth = ((uint)(20));
			// Container child alignment12.Gtk.Container+ContainerChild
			this.label21 = new global::Gtk.Label();
			this.label21.Name = "label21";
			this.label21.LabelProp = global::Mono.Unix.Catalog.GetString("label21");
			this.alignment12.Add(this.label21);
			this.vbox6.Add(this.alignment12);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.alignment12]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox10 = new global::Gtk.HBox();
			this.hbox10.Name = "hbox10";
			this.hbox10.Spacing = 6;
			// Container child hbox10.Gtk.Box+BoxChild
			this.alignment14 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment14.Name = "alignment14";
			// Container child alignment14.Gtk.Container+ContainerChild
			this.alignment16 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment16.Name = "alignment16";
			this.alignment16.RightPadding = ((uint)(165));
			// Container child alignment16.Gtk.Container+ContainerChild
			this.label23 = new global::Gtk.Label();
			this.label23.Name = "label23";
			this.alignment16.Add(this.label23);
			this.alignment14.Add(this.alignment16);
			this.hbox10.Add(this.alignment14);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.alignment14]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox10.Gtk.Box+BoxChild
			this.vbox7 = new global::Gtk.VBox();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.vbox9 = new global::Gtk.VBox();
			this.vbox9.Name = "vbox9";
			this.vbox9.Spacing = 6;
			// Container child vbox9.Gtk.Box+BoxChild
			this.hbox12 = new global::Gtk.HBox();
			this.hbox12.Name = "hbox12";
			this.hbox12.Spacing = 6;
			// Container child hbox12.Gtk.Box+BoxChild
			this.label16 = new global::Gtk.Label();
			this.label16.Name = "label16";
			this.label16.LabelProp = global::Mono.Unix.Catalog.GetString("label16");
			this.hbox12.Add(this.label16);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.label16]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox12.Gtk.Box+BoxChild
			this.image1 = new global::Gtk.Image();
			this.image1.Name = "image1";
			this.image1.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-apply", global::Gtk.IconSize.Menu);
			this.hbox12.Add(this.image1);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.image1]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			this.vbox9.Add(this.hbox12);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.hbox12]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.hbox13 = new global::Gtk.HBox();
			this.hbox13.Name = "hbox13";
			this.hbox13.Spacing = 6;
			// Container child hbox13.Gtk.Box+BoxChild
			this.label17 = new global::Gtk.Label();
			this.label17.Name = "label17";
			this.label17.LabelProp = global::Mono.Unix.Catalog.GetString("label17");
			this.hbox13.Add(this.label17);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.label17]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Container child hbox13.Gtk.Box+BoxChild
			this.image2 = new global::Gtk.Image();
			this.image2.Name = "image2";
			this.image2.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-apply", global::Gtk.IconSize.Menu);
			this.hbox13.Add(this.image2);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.image2]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			this.vbox9.Add(this.hbox13);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.hbox13]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			this.vbox7.Add(this.vbox9);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.vbox9]));
			w12.Position = 0;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.vbox8 = new global::Gtk.VBox();
			this.vbox8.Name = "vbox8";
			this.vbox8.Spacing = 6;
			// Container child vbox8.Gtk.Box+BoxChild
			this.hbox14 = new global::Gtk.HBox();
			this.hbox14.Name = "hbox14";
			this.hbox14.Spacing = 6;
			// Container child hbox14.Gtk.Box+BoxChild
			this.label18 = new global::Gtk.Label();
			this.label18.Name = "label18";
			this.label18.LabelProp = global::Mono.Unix.Catalog.GetString("label18");
			this.hbox14.Add(this.label18);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox14[this.label18]));
			w13.Position = 0;
			w13.Expand = false;
			w13.Fill = false;
			// Container child hbox14.Gtk.Box+BoxChild
			this.image3 = new global::Gtk.Image();
			this.image3.Name = "image3";
			this.image3.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-apply", global::Gtk.IconSize.Menu);
			this.hbox14.Add(this.image3);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox14[this.image3]));
			w14.Position = 1;
			w14.Expand = false;
			w14.Fill = false;
			this.vbox8.Add(this.hbox14);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.hbox14]));
			w15.Position = 0;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.hbox15 = new global::Gtk.HBox();
			this.hbox15.Name = "hbox15";
			this.hbox15.Spacing = 6;
			// Container child hbox15.Gtk.Box+BoxChild
			this.label19 = new global::Gtk.Label();
			this.label19.Name = "label19";
			this.label19.LabelProp = global::Mono.Unix.Catalog.GetString("label19");
			this.hbox15.Add(this.label19);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox15[this.label19]));
			w16.Position = 0;
			w16.Expand = false;
			w16.Fill = false;
			// Container child hbox15.Gtk.Box+BoxChild
			this.image4 = new global::Gtk.Image();
			this.image4.Name = "image4";
			this.image4.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-apply", global::Gtk.IconSize.Menu);
			this.hbox15.Add(this.image4);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox15[this.image4]));
			w17.Position = 1;
			w17.Expand = false;
			w17.Fill = false;
			this.vbox8.Add(this.hbox15);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.hbox15]));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			this.vbox7.Add(this.vbox8);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.vbox8]));
			w19.Position = 1;
			w19.Expand = false;
			w19.Fill = false;
			this.hbox10.Add(this.vbox7);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.vbox7]));
			w20.Position = 1;
			w20.Expand = false;
			w20.Fill = false;
			// Container child hbox10.Gtk.Box+BoxChild
			this.alignment13 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment13.Name = "alignment13";
			// Container child alignment13.Gtk.Container+ContainerChild
			this.label22 = new global::Gtk.Label();
			this.label22.Name = "label22";
			this.alignment13.Add(this.label22);
			this.hbox10.Add(this.alignment13);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.alignment13]));
			w22.Position = 2;
			w22.Expand = false;
			w22.Fill = false;
			this.vbox6.Add(this.hbox10);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox10]));
			w23.Position = 1;
			w23.Expand = false;
			w23.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox16 = new global::Gtk.HBox();
			this.hbox16.Name = "hbox16";
			this.hbox16.Spacing = 6;
			// Container child hbox16.Gtk.Box+BoxChild
			this.alignment17 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment17.Name = "alignment17";
			this.alignment17.RightPadding = ((uint)(75));
			// Container child alignment17.Gtk.Container+ContainerChild
			this.label25 = new global::Gtk.Label();
			this.label25.Name = "label25";
			this.alignment17.Add(this.label25);
			this.hbox16.Add(this.alignment17);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox16[this.alignment17]));
			w25.Position = 0;
			w25.Expand = false;
			w25.Fill = false;
			// Container child hbox16.Gtk.Box+BoxChild
			this.hbox17 = new global::Gtk.HBox();
			this.hbox17.Name = "hbox17";
			this.hbox17.Spacing = 6;
			// Container child hbox17.Gtk.Box+BoxChild
			this.alignment11 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment11.Name = "alignment11";
			this.alignment11.BorderWidth = ((uint)(20));
			// Container child alignment11.Gtk.Container+ContainerChild
			this.button6 = new global::Gtk.Button();
			this.button6.CanFocus = true;
			this.button6.Name = "button6";
			this.button6.UseUnderline = true;
			this.button6.Label = global::Mono.Unix.Catalog.GetString("GtkButton");
			this.alignment11.Add(this.button6);
			this.hbox17.Add(this.alignment11);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox17[this.alignment11]));
			w27.Position = 0;
			w27.Expand = false;
			w27.Fill = false;
			// Container child hbox17.Gtk.Box+BoxChild
			this.alignment10 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment10.Name = "alignment10";
			this.alignment10.BorderWidth = ((uint)(20));
			// Container child alignment10.Gtk.Container+ContainerChild
			this.button5 = new global::Gtk.Button();
			this.button5.CanFocus = true;
			this.button5.Name = "button5";
			this.button5.UseUnderline = true;
			this.button5.Label = global::Mono.Unix.Catalog.GetString("GtkButton");
			this.alignment10.Add(this.button5);
			this.hbox17.Add(this.alignment10);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox17[this.alignment10]));
			w29.Position = 1;
			w29.Expand = false;
			w29.Fill = false;
			this.hbox16.Add(this.hbox17);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox16[this.hbox17]));
			w30.Position = 1;
			w30.Expand = false;
			w30.Fill = false;
			// Container child hbox16.Gtk.Box+BoxChild
			this.alignment15 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment15.Name = "alignment15";
			// Container child alignment15.Gtk.Container+ContainerChild
			this.label24 = new global::Gtk.Label();
			this.label24.Name = "label24";
			this.alignment15.Add(this.label24);
			this.hbox16.Add(this.alignment15);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hbox16[this.alignment15]));
			w32.Position = 2;
			w32.Expand = false;
			w32.Fill = false;
			this.vbox6.Add(this.hbox16);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox16]));
			w33.Position = 2;
			w33.Expand = false;
			w33.Fill = false;
			this.Add(this.vbox6);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 240;
			this.Show();
		}
	}
}
