
// This file has been generated by the GUI designer. Do not modify.
namespace SistemaEyS.AdminForms.Tables.EmpPanelBtn
{
	public partial class AddBtn
	{
		private global::Gtk.Alignment alignment1;

		private global::Gtk.VBox vbox2;

		private global::Gtk.VBox vbox3;

		private global::Gtk.Alignment alignment2;

		private global::Gtk.VBox vbox1;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Button BtnNewIDUpdate;

		private global::Gtk.Entry TxtID;

		private global::Gtk.Label label1;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Entry TxtName;

		private global::Gtk.Label label2;

		private global::Gtk.HBox hbox3;

		private global::Gtk.Entry TxtSecondName;

		private global::Gtk.Label label3;

		private global::Gtk.HBox hbox4;

		private global::Gtk.Entry TxtLastName;

		private global::Gtk.Label label4;

		private global::Gtk.HBox hbox7;

		private global::Gtk.Entry TxtSecondLastName;

		private global::Gtk.Label label5;

		private global::Gtk.HBox hbox6;

		private global::SistemaEySLibrary.NumericEntry TxtPIN;

		private global::Gtk.Label label6;

		private global::Gtk.Alignment alignment3;

		private global::Gtk.HBox hbox5;

		private global::Gtk.Button BtnAdd;

		private global::Gtk.Button BtnCancel;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget SistemaEyS.AdminForms.Tables.EmpPanelBtn.AddBtn
			this.Name = "SistemaEyS.AdminForms.Tables.EmpPanelBtn.AddBtn";
			this.Title = global::Mono.Unix.Catalog.GetString("Añadir Empleado");
			this.WindowPosition = ((global::Gtk.WindowPosition)(2));
			// Container child SistemaEyS.AdminForms.Tables.EmpPanelBtn.AddBtn.Gtk.Container+ContainerChild
			this.alignment1 = new global::Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
			this.alignment1.Name = "alignment1";
			this.alignment1.BorderWidth = ((uint)(10));
			// Container child alignment1.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.alignment2 = new global::Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
			this.alignment2.Name = "alignment2";
			// Container child alignment2.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.BtnNewIDUpdate = new global::Gtk.Button();
			this.BtnNewIDUpdate.CanFocus = true;
			this.BtnNewIDUpdate.Name = "BtnNewIDUpdate";
			this.BtnNewIDUpdate.UseUnderline = true;
			global::Gtk.Image w1 = new global::Gtk.Image();
			w1.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-refresh", global::Gtk.IconSize.Menu);
			this.BtnNewIDUpdate.Image = w1;
			this.hbox2.Add(this.BtnNewIDUpdate);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.BtnNewIDUpdate]));
			w2.PackType = ((global::Gtk.PackType)(1));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.TxtID = new global::Gtk.Entry();
			this.TxtID.CanFocus = true;
			this.TxtID.Name = "TxtID";
			this.TxtID.IsEditable = true;
			this.TxtID.WidthChars = 20;
			this.TxtID.InvisibleChar = '•';
			this.hbox2.Add(this.TxtID);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.TxtID]));
			w3.PackType = ((global::Gtk.PackType)(1));
			w3.Position = 1;
			w3.Expand = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.Xalign = 1F;
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("ID:");
			this.label1.Justify = ((global::Gtk.Justification)(1));
			this.hbox2.Add(this.label1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.label1]));
			w4.PackType = ((global::Gtk.PackType)(1));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			this.vbox1.Add(this.hbox2);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.TxtName = new global::Gtk.Entry();
			this.TxtName.CanFocus = true;
			this.TxtName.Name = "TxtName";
			this.TxtName.IsEditable = true;
			this.TxtName.WidthChars = 25;
			this.TxtName.InvisibleChar = '•';
			this.hbox1.Add(this.TxtName);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.TxtName]));
			w6.PackType = ((global::Gtk.PackType)(1));
			w6.Position = 0;
			w6.Expand = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Nombre:");
			this.hbox1.Add(this.label2);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.label2]));
			w7.PackType = ((global::Gtk.PackType)(1));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			this.vbox1.Add(this.hbox1);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.TxtSecondName = new global::Gtk.Entry();
			this.TxtSecondName.CanFocus = true;
			this.TxtSecondName.Name = "TxtSecondName";
			this.TxtSecondName.IsEditable = true;
			this.TxtSecondName.WidthChars = 25;
			this.TxtSecondName.InvisibleChar = '•';
			this.hbox3.Add(this.TxtSecondName);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.TxtSecondName]));
			w9.PackType = ((global::Gtk.PackType)(1));
			w9.Position = 0;
			w9.Expand = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Segundo Nombre:");
			this.hbox3.Add(this.label3);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.label3]));
			w10.PackType = ((global::Gtk.PackType)(1));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			this.vbox1.Add(this.hbox3);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox3]));
			w11.Position = 2;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.TxtLastName = new global::Gtk.Entry();
			this.TxtLastName.CanFocus = true;
			this.TxtLastName.Name = "TxtLastName";
			this.TxtLastName.IsEditable = true;
			this.TxtLastName.WidthChars = 25;
			this.TxtLastName.InvisibleChar = '•';
			this.hbox4.Add(this.TxtLastName);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.TxtLastName]));
			w12.PackType = ((global::Gtk.PackType)(1));
			w12.Position = 0;
			w12.Expand = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Apellido:");
			this.hbox4.Add(this.label4);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.label4]));
			w13.PackType = ((global::Gtk.PackType)(1));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			this.vbox1.Add(this.hbox4);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox4]));
			w14.Position = 3;
			w14.Expand = false;
			w14.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.TxtSecondLastName = new global::Gtk.Entry();
			this.TxtSecondLastName.CanFocus = true;
			this.TxtSecondLastName.Name = "TxtSecondLastName";
			this.TxtSecondLastName.IsEditable = true;
			this.TxtSecondLastName.WidthChars = 25;
			this.TxtSecondLastName.InvisibleChar = '•';
			this.hbox7.Add(this.TxtSecondLastName);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.TxtSecondLastName]));
			w15.PackType = ((global::Gtk.PackType)(1));
			w15.Position = 0;
			w15.Expand = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Segundo Apellido:");
			this.hbox7.Add(this.label5);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.label5]));
			w16.PackType = ((global::Gtk.PackType)(1));
			w16.Position = 1;
			w16.Expand = false;
			w16.Fill = false;
			this.vbox1.Add(this.hbox7);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox7]));
			w17.Position = 4;
			w17.Expand = false;
			w17.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.TxtPIN = new global::SistemaEySLibrary.NumericEntry();
			this.TxtPIN.CanFocus = true;
			this.TxtPIN.Name = "TxtPIN";
			this.TxtPIN.IsEditable = true;
			this.TxtPIN.WidthChars = 25;
			this.TxtPIN.InvisibleChar = '●';
			this.hbox6.Add(this.TxtPIN);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.TxtPIN]));
			w18.PackType = ((global::Gtk.PackType)(1));
			w18.Position = 0;
			w18.Expand = false;
			w18.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("PIN:");
			this.label6.Justify = ((global::Gtk.Justification)(1));
			this.hbox6.Add(this.label6);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.label6]));
			w19.PackType = ((global::Gtk.PackType)(1));
			w19.Position = 1;
			w19.Expand = false;
			w19.Fill = false;
			this.vbox1.Add(this.hbox6);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox6]));
			w20.Position = 5;
			w20.Expand = false;
			w20.Fill = false;
			this.alignment2.Add(this.vbox1);
			this.vbox3.Add(this.alignment2);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.alignment2]));
			w22.Position = 0;
			w22.Expand = false;
			w22.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.alignment3 = new global::Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
			this.alignment3.Name = "alignment3";
			this.alignment3.TopPadding = ((uint)(20));
			// Container child alignment3.Gtk.Container+ContainerChild
			this.hbox5 = new global::Gtk.HBox();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 10;
			// Container child hbox5.Gtk.Box+BoxChild
			this.BtnAdd = new global::Gtk.Button();
			this.BtnAdd.CanFocus = true;
			this.BtnAdd.Name = "BtnAdd";
			this.BtnAdd.UseUnderline = true;
			this.BtnAdd.Label = global::Mono.Unix.Catalog.GetString("Agregar");
			this.hbox5.Add(this.BtnAdd);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.BtnAdd]));
			w23.Position = 0;
			w23.Expand = false;
			w23.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.BtnCancel = new global::Gtk.Button();
			this.BtnCancel.CanFocus = true;
			this.BtnCancel.Name = "BtnCancel";
			this.BtnCancel.UseUnderline = true;
			this.BtnCancel.Label = global::Mono.Unix.Catalog.GetString("Cancelar");
			this.hbox5.Add(this.BtnCancel);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.BtnCancel]));
			w24.Position = 1;
			w24.Expand = false;
			w24.Fill = false;
			this.alignment3.Add(this.hbox5);
			this.vbox3.Add(this.alignment3);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.alignment3]));
			w26.Position = 1;
			w26.Expand = false;
			w26.Fill = false;
			this.vbox2.Add(this.vbox3);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.vbox3]));
			w27.Position = 0;
			w27.Expand = false;
			w27.Fill = false;
			this.alignment1.Add(this.vbox2);
			this.Add(this.alignment1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 415;
			this.DefaultHeight = 312;
			this.Show();
			this.BtnNewIDUpdate.Clicked += new global::System.EventHandler(this.BtnNewIDUpdateOnClicked);
			this.BtnAdd.Clicked += new global::System.EventHandler(this.BtnAddOnClicked);
			this.BtnCancel.Clicked += new global::System.EventHandler(this.BtnCancelOnClicked);
		}
	}
}
