
// This file has been generated by the GUI designer. Do not modify.
namespace SistemaEyS.AdminForms.Reports
{
	public partial class DepartamentoReport
	{
		private global::Gtk.Alignment alignment1;

		private global::Gtk.VBox vbox1;

		private global::Gtk.VBox vbox2;

		private global::Gtk.Alignment alignment2;

		private global::Gtk.Label label1;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::SistemaEySLibrary.ViewTableTemplate viewTable;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Button BtnExit;

		private global::Gtk.Button BtnSave;

		private global::Gtk.Button BtnRefresh;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget SistemaEyS.AdminForms.Reports.DepartamentoReport
			this.Name = "SistemaEyS.AdminForms.Reports.DepartamentoReport";
			this.Title = global::Mono.Unix.Catalog.GetString("DepartamentoReport");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child SistemaEyS.AdminForms.Reports.DepartamentoReport.Gtk.Container+ContainerChild
			this.alignment1 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment1.Name = "alignment1";
			this.alignment1.LeftPadding = ((uint)(10));
			this.alignment1.TopPadding = ((uint)(10));
			this.alignment1.RightPadding = ((uint)(10));
			this.alignment1.BottomPadding = ((uint)(10));
			// Container child alignment1.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.alignment2 = new global::Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
			this.alignment2.HeightRequest = 50;
			this.alignment2.Name = "alignment2";
			// Container child alignment2.Gtk.Container+ContainerChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("<span weight=\"bold\" size=\"large\">Departamentos</span>");
			this.label1.UseMarkup = true;
			this.alignment2.Add(this.label1);
			this.vbox2.Add(this.alignment2);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.alignment2]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.viewTable = new global::SistemaEySLibrary.ViewTableTemplate();
			this.viewTable.CanFocus = true;
			this.viewTable.Name = "viewTable";
			this.GtkScrolledWindow.Add(this.viewTable);
			this.vbox2.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.GtkScrolledWindow]));
			w4.Position = 1;
			this.vbox1.Add(this.vbox2);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.vbox2]));
			w5.Position = 0;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.BtnExit = new global::Gtk.Button();
			this.BtnExit.CanFocus = true;
			this.BtnExit.Name = "BtnExit";
			this.BtnExit.UseUnderline = true;
			this.BtnExit.Label = global::Mono.Unix.Catalog.GetString("Salir");
			global::Gtk.Image w6 = new global::Gtk.Image();
			w6.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-quit", global::Gtk.IconSize.Menu);
			this.BtnExit.Image = w6;
			this.hbox1.Add(this.BtnExit);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.BtnExit]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.BtnSave = new global::Gtk.Button();
			this.BtnSave.CanFocus = true;
			this.BtnSave.Name = "BtnSave";
			this.BtnSave.UseUnderline = true;
			this.BtnSave.Label = global::Mono.Unix.Catalog.GetString("Guardar");
			global::Gtk.Image w8 = new global::Gtk.Image();
			w8.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-save-as", global::Gtk.IconSize.Menu);
			this.BtnSave.Image = w8;
			this.hbox1.Add(this.BtnSave);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.BtnSave]));
			w9.PackType = ((global::Gtk.PackType)(1));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.BtnRefresh = new global::Gtk.Button();
			this.BtnRefresh.CanFocus = true;
			this.BtnRefresh.Name = "BtnRefresh";
			this.BtnRefresh.UseUnderline = true;
			this.BtnRefresh.Label = global::Mono.Unix.Catalog.GetString("Actualizar");
			global::Gtk.Image w10 = new global::Gtk.Image();
			w10.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-refresh", global::Gtk.IconSize.Menu);
			this.BtnRefresh.Image = w10;
			this.hbox1.Add(this.BtnRefresh);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.BtnRefresh]));
			w11.PackType = ((global::Gtk.PackType)(1));
			w11.Position = 2;
			w11.Expand = false;
			w11.Fill = false;
			this.vbox1.Add(this.hbox1);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
			w12.Position = 1;
			w12.Expand = false;
			w12.Fill = false;
			this.alignment1.Add(this.vbox1);
			this.Add(this.alignment1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
			this.BtnExit.Clicked += new global::System.EventHandler(this.OnBtnExitClicked);
			this.BtnRefresh.Clicked += new global::System.EventHandler(this.OnBtnRefreshClicked);
			this.BtnSave.Clicked += new global::System.EventHandler(this.OnBtnSaveClicked);
		}
	}
}
