
// This file has been generated by the GUI designer. Do not modify.
namespace SistemaEyS.UserForms
{
	public partial class UserAssistanceForm
	{
		private global::Gtk.Alignment mainLayout;

		private global::Gtk.VBox mainVerticalBox;

		private global::Gtk.Alignment alignment9;

		private global::Gtk.VBox vbox8;

		private global::Gtk.Label lbWelcome;

		private global::Gtk.HBox btnHBoxWrapper;

		private global::Gtk.Label label12;

		private global::Gtk.HBox btnHBox;

		private global::Gtk.Button btnMarkEntry;

		private global::Gtk.Button btnMarkExit;

		private global::Gtk.Label label11;

		private global::Gtk.Alignment exitBtnAlignment;

		private global::Gtk.Button btnExit;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget SistemaEyS.UserForms.UserAssistanceForm
			this.Name = "SistemaEyS.UserForms.UserAssistanceForm";
			this.Title = global::Mono.Unix.Catalog.GetString("UserAssistanceForm");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child SistemaEyS.UserForms.UserAssistanceForm.Gtk.Container+ContainerChild
			this.mainLayout = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.mainLayout.Name = "mainLayout";
			this.mainLayout.LeftPadding = ((uint)(10));
			this.mainLayout.TopPadding = ((uint)(10));
			this.mainLayout.RightPadding = ((uint)(10));
			this.mainLayout.BottomPadding = ((uint)(10));
			// Container child mainLayout.Gtk.Container+ContainerChild
			this.mainVerticalBox = new global::Gtk.VBox();
			this.mainVerticalBox.Name = "mainVerticalBox";
			this.mainVerticalBox.Spacing = 6;
			// Container child mainVerticalBox.Gtk.Box+BoxChild
			this.alignment9 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment9.Name = "alignment9";
			// Container child alignment9.Gtk.Container+ContainerChild
			this.vbox8 = new global::Gtk.VBox();
			this.vbox8.Name = "vbox8";
			this.vbox8.Spacing = 30;
			// Container child vbox8.Gtk.Box+BoxChild
			this.lbWelcome = new global::Gtk.Label();
			this.lbWelcome.Name = "lbWelcome";
			this.lbWelcome.LabelProp = global::Mono.Unix.Catalog.GetString("!Bienvenido, USUARIO!");
			this.lbWelcome.Justify = ((global::Gtk.Justification)(2));
			this.vbox8.Add(this.lbWelcome);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.lbWelcome]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.btnHBoxWrapper = new global::Gtk.HBox();
			this.btnHBoxWrapper.Name = "btnHBoxWrapper";
			this.btnHBoxWrapper.Spacing = 6;
			// Container child btnHBoxWrapper.Gtk.Box+BoxChild
			this.label12 = new global::Gtk.Label();
			this.label12.Name = "label12";
			this.btnHBoxWrapper.Add(this.label12);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.btnHBoxWrapper[this.label12]));
			w2.Position = 0;
			w2.Fill = false;
			// Container child btnHBoxWrapper.Gtk.Box+BoxChild
			this.btnHBox = new global::Gtk.HBox();
			this.btnHBox.Name = "btnHBox";
			this.btnHBox.Spacing = 6;
			// Container child btnHBox.Gtk.Box+BoxChild
			this.btnMarkEntry = new global::Gtk.Button();
			this.btnMarkEntry.CanFocus = true;
			this.btnMarkEntry.Name = "btnMarkEntry";
			this.btnMarkEntry.UseUnderline = true;
			this.btnMarkEntry.Label = global::Mono.Unix.Catalog.GetString("Marcar Entrada");
			this.btnHBox.Add(this.btnMarkEntry);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.btnHBox[this.btnMarkEntry]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child btnHBox.Gtk.Box+BoxChild
			this.btnMarkExit = new global::Gtk.Button();
			this.btnMarkExit.CanFocus = true;
			this.btnMarkExit.Name = "btnMarkExit";
			this.btnMarkExit.UseUnderline = true;
			this.btnMarkExit.Label = global::Mono.Unix.Catalog.GetString("Marcar Salida");
			this.btnHBox.Add(this.btnMarkExit);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.btnHBox[this.btnMarkExit]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			this.btnHBoxWrapper.Add(this.btnHBox);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.btnHBoxWrapper[this.btnHBox]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			// Container child btnHBoxWrapper.Gtk.Box+BoxChild
			this.label11 = new global::Gtk.Label();
			this.label11.Name = "label11";
			this.btnHBoxWrapper.Add(this.label11);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.btnHBoxWrapper[this.label11]));
			w6.Position = 2;
			w6.Fill = false;
			this.vbox8.Add(this.btnHBoxWrapper);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.btnHBoxWrapper]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			this.alignment9.Add(this.vbox8);
			this.mainVerticalBox.Add(this.alignment9);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.mainVerticalBox[this.alignment9]));
			w9.Position = 0;
			w9.Fill = false;
			// Container child mainVerticalBox.Gtk.Box+BoxChild
			this.exitBtnAlignment = new global::Gtk.Alignment(0F, 1F, 0F, 0F);
			this.exitBtnAlignment.Name = "exitBtnAlignment";
			// Container child exitBtnAlignment.Gtk.Container+ContainerChild
			this.btnExit = new global::Gtk.Button();
			this.btnExit.CanFocus = true;
			this.btnExit.Name = "btnExit";
			this.btnExit.UseUnderline = true;
			this.btnExit.Label = global::Mono.Unix.Catalog.GetString("Salir");
			this.exitBtnAlignment.Add(this.btnExit);
			this.mainVerticalBox.Add(this.exitBtnAlignment);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.mainVerticalBox[this.exitBtnAlignment]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			this.mainLayout.Add(this.mainVerticalBox);
			this.Add(this.mainLayout);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 517;
			this.DefaultHeight = 306;
			this.Show();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
			this.btnExit.Clicked += new global::System.EventHandler(this.btnExitOnClicked);
		}
	}
}
