
// This file has been generated by the GUI designer. Do not modify.
namespace SistemaEyS.AdminForms.Settings
{
	public partial class HorarioSenttings
	{
		private global::Gtk.VBox vbox1;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget SistemaEyS.AdminForms.Settings.HorarioSenttings
			this.Name = "SistemaEyS.AdminForms.Settings.HorarioSenttings";
			this.Title = global::Mono.Unix.Catalog.GetString("HorarioSenttings");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child SistemaEyS.AdminForms.Settings.HorarioSenttings.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Spacing = 6;
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
