
// This file has been generated by the GUI designer. Do not modify.
namespace SistemaEyS.AdminForms.Tables
{
	public partial class EmpleadosPanel
	{
		private global::Gtk.Alignment alignment5;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView treeView;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget SistemaEyS.AdminForms.Tables.EmpleadosPanel
			global::Stetic.BinContainer.Attach(this);
			this.Name = "SistemaEyS.AdminForms.Tables.EmpleadosPanel";
			// Container child SistemaEyS.AdminForms.Tables.EmpleadosPanel.Gtk.Container+ContainerChild
			this.alignment5 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment5.Name = "alignment5";
			this.alignment5.LeftPadding = ((uint)(10));
			this.alignment5.TopPadding = ((uint)(10));
			this.alignment5.RightPadding = ((uint)(10));
			this.alignment5.BottomPadding = ((uint)(10));
			// Container child alignment5.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treeView = new global::Gtk.TreeView();
			this.treeView.CanFocus = true;
			this.treeView.Name = "treeView";
			this.treeView.RulesHint = true;
			this.GtkScrolledWindow.Add(this.treeView);
			this.alignment5.Add(this.GtkScrolledWindow);
			this.Add(this.alignment5);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
