
// This file has been generated by the GUI designer. Do not modify.
namespace SistemaEyS.AdminForms.Panels
{
	public partial class EmpleadosPanel
	{
		private global::Gtk.Alignment alignment5;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.NodeView nodeview2;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget SistemaEyS.AdminForms.Panels.EmpleadosPanel
			global::Stetic.BinContainer.Attach(this);
			this.Name = "SistemaEyS.AdminForms.Panels.EmpleadosPanel";
			// Container child SistemaEyS.AdminForms.Panels.EmpleadosPanel.Gtk.Container+ContainerChild
			this.alignment5 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment5.Name = "alignment5";
			this.alignment5.LeftPadding = ((uint)(10));
			this.alignment5.TopPadding = ((uint)(10));
			this.alignment5.RightPadding = ((uint)(10));
			this.alignment5.BottomPadding = ((uint)(10));
			// Container child alignment5.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.nodeview2 = new global::Gtk.NodeView();
			this.nodeview2.CanFocus = true;
			this.nodeview2.Name = "nodeview2";
			this.GtkScrolledWindow.Add(this.nodeview2);
			this.alignment5.Add(this.GtkScrolledWindow);
			this.Add(this.alignment5);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
